/* Generated by Yosys 0.65+59 (git sha1 94ec78b6e, g++ 13.3.0-6ubuntu2~24.04.1 -fPIC -O3) */

module fifo_sync(clk, rst_n, cs, wr_en, rd_en, data_in, data_out, empty, full);
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  input cs;
  wire cs;
  input wr_en;
  wire wr_en;
  input rd_en;
  wire rd_en;
  input [7:0] data_in;
  wire [7:0] data_in;
  output [7:0] data_out;
  wire [7:0] data_out;
  output empty;
  wire empty;
  output full;
  wire full;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire [3:0] _228_;
  wire [3:0] _229_;
  wire [7:0] \fifo[0] ;
  wire [7:0] \fifo[1] ;
  wire [7:0] \fifo[2] ;
  wire [7:0] \fifo[3] ;
  wire [7:0] \fifo[4] ;
  wire [7:0] \fifo[5] ;
  wire [7:0] \fifo[6] ;
  wire [7:0] \fifo[7] ;
  wire [3:0] read_pointer;
  wire [3:0] write_pointer;
  INV_X1 _230_ (
    .A(rst_n),
    .ZN(_084_)
  );
  NOR2_X1 _231_ (
    .A1(_228_[0]),
    .A2(write_pointer[1]),
    .ZN(_085_)
  );
  XOR2_X1 _232_ (
    .A(read_pointer[0]),
    .B(write_pointer[0]),
    .Z(_086_)
  );
  XOR2_X1 _233_ (
    .A(read_pointer[2]),
    .B(write_pointer[2]),
    .Z(_087_)
  );
  XOR2_X1 _234_ (
    .A(read_pointer[1]),
    .B(write_pointer[1]),
    .Z(_088_)
  );
  XNOR2_X1 _235_ (
    .A(read_pointer[3]),
    .B(write_pointer[3]),
    .ZN(_089_)
  );
  XOR2_X1 _236_ (
    .A(read_pointer[3]),
    .B(write_pointer[3]),
    .Z(_090_)
  );
  NOR4_X1 _237_ (
    .A1(_086_),
    .A2(_087_),
    .A3(_088_),
    .A4(_089_),
    .ZN(full)
  );
  NAND2_X1 _238_ (
    .A1(cs),
    .A2(wr_en),
    .ZN(_091_)
  );
  NOR2_X1 _239_ (
    .A1(full),
    .A2(_091_),
    .ZN(_092_)
  );
  NOR4_X1 _240_ (
    .A1(write_pointer[2]),
    .A2(_084_),
    .A3(full),
    .A4(_091_),
    .ZN(_093_)
  );
  NAND2_X1 _241_ (
    .A1(_085_),
    .A2(_093_),
    .ZN(_094_)
  );
  MUX2_X1 _242_ (
    .A(data_in[6]),
    .B(\fifo[1] [6]),
    .S(_094_),
    .Z(_004_)
  );
  MUX2_X1 _243_ (
    .A(data_in[5]),
    .B(\fifo[1] [5]),
    .S(_094_),
    .Z(_005_)
  );
  MUX2_X1 _244_ (
    .A(data_in[4]),
    .B(\fifo[1] [4]),
    .S(_094_),
    .Z(_006_)
  );
  MUX2_X1 _245_ (
    .A(data_in[3]),
    .B(\fifo[1] [3]),
    .S(_094_),
    .Z(_007_)
  );
  MUX2_X1 _246_ (
    .A(data_in[2]),
    .B(\fifo[1] [2]),
    .S(_094_),
    .Z(_008_)
  );
  MUX2_X1 _247_ (
    .A(data_in[1]),
    .B(\fifo[1] [1]),
    .S(_094_),
    .Z(_009_)
  );
  MUX2_X1 _248_ (
    .A(data_in[0]),
    .B(\fifo[1] [0]),
    .S(_094_),
    .Z(_010_)
  );
  NOR2_X1 _249_ (
    .A1(_000_),
    .A2(write_pointer[0]),
    .ZN(_095_)
  );
  NAND2_X1 _250_ (
    .A1(_093_),
    .A2(_095_),
    .ZN(_096_)
  );
  MUX2_X1 _251_ (
    .A(data_in[6]),
    .B(\fifo[2] [6]),
    .S(_096_),
    .Z(_011_)
  );
  MUX2_X1 _252_ (
    .A(data_in[5]),
    .B(\fifo[2] [5]),
    .S(_096_),
    .Z(_012_)
  );
  MUX2_X1 _253_ (
    .A(data_in[4]),
    .B(\fifo[2] [4]),
    .S(_096_),
    .Z(_013_)
  );
  MUX2_X1 _254_ (
    .A(data_in[3]),
    .B(\fifo[2] [3]),
    .S(_096_),
    .Z(_014_)
  );
  MUX2_X1 _255_ (
    .A(data_in[2]),
    .B(\fifo[2] [2]),
    .S(_096_),
    .Z(_015_)
  );
  MUX2_X1 _256_ (
    .A(data_in[1]),
    .B(\fifo[2] [1]),
    .S(_096_),
    .Z(_016_)
  );
  MUX2_X1 _257_ (
    .A(data_in[0]),
    .B(\fifo[2] [0]),
    .S(_096_),
    .Z(_017_)
  );
  NOR2_X1 _258_ (
    .A1(_228_[0]),
    .A2(_000_),
    .ZN(_097_)
  );
  NOR4_X1 _259_ (
    .A1(_001_),
    .A2(_084_),
    .A3(full),
    .A4(_091_),
    .ZN(_098_)
  );
  NAND2_X1 _260_ (
    .A1(_097_),
    .A2(_098_),
    .ZN(_099_)
  );
  MUX2_X1 _261_ (
    .A(data_in[6]),
    .B(\fifo[7] [6]),
    .S(_099_),
    .Z(_018_)
  );
  MUX2_X1 _262_ (
    .A(data_in[5]),
    .B(\fifo[7] [5]),
    .S(_099_),
    .Z(_019_)
  );
  MUX2_X1 _263_ (
    .A(data_in[4]),
    .B(\fifo[7] [4]),
    .S(_099_),
    .Z(_020_)
  );
  MUX2_X1 _264_ (
    .A(data_in[3]),
    .B(\fifo[7] [3]),
    .S(_099_),
    .Z(_021_)
  );
  MUX2_X1 _265_ (
    .A(data_in[2]),
    .B(\fifo[7] [2]),
    .S(_099_),
    .Z(_022_)
  );
  MUX2_X1 _266_ (
    .A(data_in[1]),
    .B(\fifo[7] [1]),
    .S(_099_),
    .Z(_023_)
  );
  MUX2_X1 _267_ (
    .A(data_in[0]),
    .B(\fifo[7] [0]),
    .S(_099_),
    .Z(_024_)
  );
  NOR4_X1 _268_ (
    .A1(_086_),
    .A2(_087_),
    .A3(_088_),
    .A4(_090_),
    .ZN(empty)
  );
  NAND2_X1 _269_ (
    .A1(cs),
    .A2(rd_en),
    .ZN(_100_)
  );
  NOR2_X1 _270_ (
    .A1(empty),
    .A2(_100_),
    .ZN(_101_)
  );
  NOR3_X1 _271_ (
    .A1(_229_[0]),
    .A2(read_pointer[2]),
    .A3(read_pointer[1]),
    .ZN(_102_)
  );
  NOR3_X1 _272_ (
    .A1(_002_),
    .A2(read_pointer[0]),
    .A3(_003_),
    .ZN(_103_)
  );
  NOR3_X1 _273_ (
    .A1(read_pointer[1]),
    .A2(read_pointer[0]),
    .A3(_003_),
    .ZN(_104_)
  );
  NOR3_X1 _274_ (
    .A1(_229_[0]),
    .A2(_002_),
    .A3(read_pointer[2]),
    .ZN(_105_)
  );
  NOR3_X1 _275_ (
    .A1(_229_[0]),
    .A2(read_pointer[1]),
    .A3(_003_),
    .ZN(_106_)
  );
  NOR3_X1 _276_ (
    .A1(read_pointer[2]),
    .A2(read_pointer[1]),
    .A3(read_pointer[0]),
    .ZN(_107_)
  );
  NOR3_X1 _277_ (
    .A1(_002_),
    .A2(read_pointer[2]),
    .A3(read_pointer[0]),
    .ZN(_108_)
  );
  NOR3_X1 _278_ (
    .A1(_229_[0]),
    .A2(_002_),
    .A3(_003_),
    .ZN(_109_)
  );
  AOI22_X1 _279_ (
    .A1(\fifo[4] [6]),
    .A2(_104_),
    .B1(_106_),
    .B2(\fifo[5] [6]),
    .ZN(_110_)
  );
  AOI222_X1 _280_ (
    .A1(\fifo[0] [6]),
    .A2(_107_),
    .B1(_108_),
    .B2(\fifo[2] [6]),
    .C1(\fifo[3] [6]),
    .C2(_105_),
    .ZN(_111_)
  );
  AOI222_X1 _281_ (
    .A1(\fifo[1] [6]),
    .A2(_102_),
    .B1(_103_),
    .B2(\fifo[6] [6]),
    .C1(_109_),
    .C2(\fifo[7] [6]),
    .ZN(_112_)
  );
  NAND3_X1 _282_ (
    .A1(_110_),
    .A2(_111_),
    .A3(_112_),
    .ZN(_113_)
  );
  MUX2_X1 _283_ (
    .A(data_out[6]),
    .B(_113_),
    .S(_101_),
    .Z(_025_)
  );
  AOI22_X1 _284_ (
    .A1(\fifo[4] [5]),
    .A2(_104_),
    .B1(_106_),
    .B2(\fifo[5] [5]),
    .ZN(_114_)
  );
  AOI222_X1 _285_ (
    .A1(\fifo[0] [5]),
    .A2(_107_),
    .B1(_108_),
    .B2(\fifo[2] [5]),
    .C1(\fifo[3] [5]),
    .C2(_105_),
    .ZN(_115_)
  );
  AOI222_X1 _286_ (
    .A1(\fifo[1] [5]),
    .A2(_102_),
    .B1(_103_),
    .B2(\fifo[6] [5]),
    .C1(_109_),
    .C2(\fifo[7] [5]),
    .ZN(_116_)
  );
  NAND3_X1 _287_ (
    .A1(_114_),
    .A2(_115_),
    .A3(_116_),
    .ZN(_117_)
  );
  MUX2_X1 _288_ (
    .A(data_out[5]),
    .B(_117_),
    .S(_101_),
    .Z(_026_)
  );
  AOI22_X1 _289_ (
    .A1(\fifo[1] [4]),
    .A2(_102_),
    .B1(_106_),
    .B2(\fifo[5] [4]),
    .ZN(_118_)
  );
  AOI222_X1 _290_ (
    .A1(\fifo[4] [4]),
    .A2(_104_),
    .B1(_105_),
    .B2(\fifo[3] [4]),
    .C1(\fifo[2] [4]),
    .C2(_108_),
    .ZN(_119_)
  );
  AOI222_X1 _291_ (
    .A1(\fifo[6] [4]),
    .A2(_103_),
    .B1(_109_),
    .B2(\fifo[7] [4]),
    .C1(_107_),
    .C2(\fifo[0] [4]),
    .ZN(_120_)
  );
  NAND3_X1 _292_ (
    .A1(_118_),
    .A2(_119_),
    .A3(_120_),
    .ZN(_121_)
  );
  MUX2_X1 _293_ (
    .A(data_out[4]),
    .B(_121_),
    .S(_101_),
    .Z(_027_)
  );
  AOI22_X1 _294_ (
    .A1(\fifo[4] [3]),
    .A2(_104_),
    .B1(_106_),
    .B2(\fifo[5] [3]),
    .ZN(_122_)
  );
  AOI222_X1 _295_ (
    .A1(\fifo[1] [3]),
    .A2(_102_),
    .B1(_105_),
    .B2(\fifo[3] [3]),
    .C1(_108_),
    .C2(\fifo[2] [3]),
    .ZN(_123_)
  );
  AOI222_X1 _296_ (
    .A1(\fifo[6] [3]),
    .A2(_103_),
    .B1(_109_),
    .B2(\fifo[7] [3]),
    .C1(_107_),
    .C2(\fifo[0] [3]),
    .ZN(_124_)
  );
  NAND3_X1 _297_ (
    .A1(_122_),
    .A2(_123_),
    .A3(_124_),
    .ZN(_125_)
  );
  MUX2_X1 _298_ (
    .A(data_out[3]),
    .B(_125_),
    .S(_101_),
    .Z(_028_)
  );
  AOI22_X1 _299_ (
    .A1(\fifo[4] [2]),
    .A2(_104_),
    .B1(_107_),
    .B2(\fifo[0] [2]),
    .ZN(_126_)
  );
  AOI222_X1 _300_ (
    .A1(\fifo[3] [2]),
    .A2(_105_),
    .B1(_106_),
    .B2(\fifo[5] [2]),
    .C1(_108_),
    .C2(\fifo[2] [2]),
    .ZN(_127_)
  );
  AOI222_X1 _301_ (
    .A1(\fifo[1] [2]),
    .A2(_102_),
    .B1(_103_),
    .B2(\fifo[6] [2]),
    .C1(_109_),
    .C2(\fifo[7] [2]),
    .ZN(_128_)
  );
  NAND3_X1 _302_ (
    .A1(_126_),
    .A2(_127_),
    .A3(_128_),
    .ZN(_129_)
  );
  MUX2_X1 _303_ (
    .A(data_out[2]),
    .B(_129_),
    .S(_101_),
    .Z(_029_)
  );
  AOI22_X1 _304_ (
    .A1(\fifo[4] [1]),
    .A2(_104_),
    .B1(_107_),
    .B2(\fifo[0] [1]),
    .ZN(_130_)
  );
  AOI222_X1 _305_ (
    .A1(\fifo[3] [1]),
    .A2(_105_),
    .B1(_106_),
    .B2(\fifo[5] [1]),
    .C1(_108_),
    .C2(\fifo[2] [1]),
    .ZN(_131_)
  );
  AOI222_X1 _306_ (
    .A1(\fifo[1] [1]),
    .A2(_102_),
    .B1(_103_),
    .B2(\fifo[6] [1]),
    .C1(_109_),
    .C2(\fifo[7] [1]),
    .ZN(_132_)
  );
  NAND3_X1 _307_ (
    .A1(_130_),
    .A2(_131_),
    .A3(_132_),
    .ZN(_133_)
  );
  MUX2_X1 _308_ (
    .A(data_out[1]),
    .B(_133_),
    .S(_101_),
    .Z(_030_)
  );
  AOI22_X1 _309_ (
    .A1(\fifo[1] [0]),
    .A2(_102_),
    .B1(_107_),
    .B2(\fifo[0] [0]),
    .ZN(_134_)
  );
  AOI222_X1 _310_ (
    .A1(\fifo[6] [0]),
    .A2(_103_),
    .B1(_109_),
    .B2(\fifo[7] [0]),
    .C1(_106_),
    .C2(\fifo[5] [0]),
    .ZN(_135_)
  );
  AOI222_X1 _311_ (
    .A1(\fifo[4] [0]),
    .A2(_104_),
    .B1(_105_),
    .B2(\fifo[3] [0]),
    .C1(\fifo[2] [0]),
    .C2(_108_),
    .ZN(_136_)
  );
  NAND3_X1 _312_ (
    .A1(_134_),
    .A2(_135_),
    .A3(_136_),
    .ZN(_137_)
  );
  MUX2_X1 _313_ (
    .A(data_out[0]),
    .B(_137_),
    .S(_101_),
    .Z(_031_)
  );
  NAND3_X1 _314_ (
    .A1(read_pointer[1]),
    .A2(read_pointer[0]),
    .A3(_101_),
    .ZN(_138_)
  );
  NAND4_X1 _315_ (
    .A1(read_pointer[2]),
    .A2(read_pointer[1]),
    .A3(read_pointer[0]),
    .A4(_101_),
    .ZN(_139_)
  );
  XNOR2_X1 _316_ (
    .A(read_pointer[2]),
    .B(_138_),
    .ZN(_032_)
  );
  XOR2_X1 _317_ (
    .A(read_pointer[1]),
    .B(read_pointer[0]),
    .Z(_140_)
  );
  MUX2_X1 _318_ (
    .A(read_pointer[1]),
    .B(_140_),
    .S(_101_),
    .Z(_033_)
  );
  MUX2_X1 _319_ (
    .A(read_pointer[0]),
    .B(_229_[0]),
    .S(_101_),
    .Z(_034_)
  );
  NAND2_X1 _320_ (
    .A1(_095_),
    .A2(_098_),
    .ZN(_141_)
  );
  MUX2_X1 _321_ (
    .A(data_in[6]),
    .B(\fifo[6] [6]),
    .S(_141_),
    .Z(_035_)
  );
  MUX2_X1 _322_ (
    .A(data_in[5]),
    .B(\fifo[6] [5]),
    .S(_141_),
    .Z(_036_)
  );
  MUX2_X1 _323_ (
    .A(data_in[4]),
    .B(\fifo[6] [4]),
    .S(_141_),
    .Z(_037_)
  );
  MUX2_X1 _324_ (
    .A(data_in[3]),
    .B(\fifo[6] [3]),
    .S(_141_),
    .Z(_038_)
  );
  MUX2_X1 _325_ (
    .A(data_in[2]),
    .B(\fifo[6] [2]),
    .S(_141_),
    .Z(_039_)
  );
  MUX2_X1 _326_ (
    .A(data_in[1]),
    .B(\fifo[6] [1]),
    .S(_141_),
    .Z(_040_)
  );
  MUX2_X1 _327_ (
    .A(data_in[0]),
    .B(\fifo[6] [0]),
    .S(_141_),
    .Z(_041_)
  );
  NAND2_X1 _328_ (
    .A1(_085_),
    .A2(_098_),
    .ZN(_142_)
  );
  MUX2_X1 _329_ (
    .A(data_in[6]),
    .B(\fifo[5] [6]),
    .S(_142_),
    .Z(_042_)
  );
  MUX2_X1 _330_ (
    .A(data_in[5]),
    .B(\fifo[5] [5]),
    .S(_142_),
    .Z(_043_)
  );
  MUX2_X1 _331_ (
    .A(data_in[4]),
    .B(\fifo[5] [4]),
    .S(_142_),
    .Z(_044_)
  );
  MUX2_X1 _332_ (
    .A(data_in[3]),
    .B(\fifo[5] [3]),
    .S(_142_),
    .Z(_045_)
  );
  MUX2_X1 _333_ (
    .A(data_in[2]),
    .B(\fifo[5] [2]),
    .S(_142_),
    .Z(_046_)
  );
  MUX2_X1 _334_ (
    .A(data_in[1]),
    .B(\fifo[5] [1]),
    .S(_142_),
    .Z(_047_)
  );
  MUX2_X1 _335_ (
    .A(data_in[0]),
    .B(\fifo[5] [0]),
    .S(_142_),
    .Z(_048_)
  );
  NAND3_X1 _336_ (
    .A1(write_pointer[1]),
    .A2(write_pointer[0]),
    .A3(_092_),
    .ZN(_143_)
  );
  NAND4_X1 _337_ (
    .A1(write_pointer[2]),
    .A2(write_pointer[1]),
    .A3(write_pointer[0]),
    .A4(_092_),
    .ZN(_144_)
  );
  XNOR2_X1 _338_ (
    .A(write_pointer[2]),
    .B(_143_),
    .ZN(_049_)
  );
  NOR2_X1 _339_ (
    .A1(write_pointer[1]),
    .A2(write_pointer[0]),
    .ZN(_145_)
  );
  XOR2_X1 _340_ (
    .A(write_pointer[1]),
    .B(write_pointer[0]),
    .Z(_146_)
  );
  MUX2_X1 _341_ (
    .A(write_pointer[1]),
    .B(_146_),
    .S(_092_),
    .Z(_050_)
  );
  MUX2_X1 _342_ (
    .A(write_pointer[0]),
    .B(_228_[0]),
    .S(_092_),
    .Z(_051_)
  );
  NAND2_X1 _343_ (
    .A1(_093_),
    .A2(_097_),
    .ZN(_147_)
  );
  MUX2_X1 _344_ (
    .A(data_in[6]),
    .B(\fifo[3] [6]),
    .S(_147_),
    .Z(_052_)
  );
  MUX2_X1 _345_ (
    .A(data_in[5]),
    .B(\fifo[3] [5]),
    .S(_147_),
    .Z(_053_)
  );
  MUX2_X1 _346_ (
    .A(data_in[4]),
    .B(\fifo[3] [4]),
    .S(_147_),
    .Z(_054_)
  );
  MUX2_X1 _347_ (
    .A(data_in[3]),
    .B(\fifo[3] [3]),
    .S(_147_),
    .Z(_055_)
  );
  MUX2_X1 _348_ (
    .A(data_in[2]),
    .B(\fifo[3] [2]),
    .S(_147_),
    .Z(_056_)
  );
  MUX2_X1 _349_ (
    .A(data_in[1]),
    .B(\fifo[3] [1]),
    .S(_147_),
    .Z(_057_)
  );
  MUX2_X1 _350_ (
    .A(data_in[0]),
    .B(\fifo[3] [0]),
    .S(_147_),
    .Z(_058_)
  );
  NAND2_X1 _351_ (
    .A1(_093_),
    .A2(_145_),
    .ZN(_148_)
  );
  MUX2_X1 _352_ (
    .A(data_in[6]),
    .B(\fifo[0] [6]),
    .S(_148_),
    .Z(_059_)
  );
  MUX2_X1 _353_ (
    .A(data_in[5]),
    .B(\fifo[0] [5]),
    .S(_148_),
    .Z(_060_)
  );
  MUX2_X1 _354_ (
    .A(data_in[4]),
    .B(\fifo[0] [4]),
    .S(_148_),
    .Z(_061_)
  );
  MUX2_X1 _355_ (
    .A(data_in[3]),
    .B(\fifo[0] [3]),
    .S(_148_),
    .Z(_062_)
  );
  MUX2_X1 _356_ (
    .A(data_in[2]),
    .B(\fifo[0] [2]),
    .S(_148_),
    .Z(_063_)
  );
  MUX2_X1 _357_ (
    .A(data_in[1]),
    .B(\fifo[0] [1]),
    .S(_148_),
    .Z(_064_)
  );
  MUX2_X1 _358_ (
    .A(data_in[0]),
    .B(\fifo[0] [0]),
    .S(_148_),
    .Z(_065_)
  );
  NAND2_X1 _359_ (
    .A1(_098_),
    .A2(_145_),
    .ZN(_149_)
  );
  MUX2_X1 _360_ (
    .A(data_in[6]),
    .B(\fifo[4] [6]),
    .S(_149_),
    .Z(_066_)
  );
  MUX2_X1 _361_ (
    .A(data_in[5]),
    .B(\fifo[4] [5]),
    .S(_149_),
    .Z(_067_)
  );
  MUX2_X1 _362_ (
    .A(data_in[4]),
    .B(\fifo[4] [4]),
    .S(_149_),
    .Z(_068_)
  );
  MUX2_X1 _363_ (
    .A(data_in[3]),
    .B(\fifo[4] [3]),
    .S(_149_),
    .Z(_069_)
  );
  MUX2_X1 _364_ (
    .A(data_in[2]),
    .B(\fifo[4] [2]),
    .S(_149_),
    .Z(_070_)
  );
  MUX2_X1 _365_ (
    .A(data_in[1]),
    .B(\fifo[4] [1]),
    .S(_149_),
    .Z(_071_)
  );
  MUX2_X1 _366_ (
    .A(data_in[0]),
    .B(\fifo[4] [0]),
    .S(_149_),
    .Z(_072_)
  );
  MUX2_X1 _367_ (
    .A(data_in[7]),
    .B(\fifo[2] [7]),
    .S(_096_),
    .Z(_073_)
  );
  MUX2_X1 _368_ (
    .A(data_in[7]),
    .B(\fifo[7] [7]),
    .S(_099_),
    .Z(_074_)
  );
  AOI22_X1 _369_ (
    .A1(\fifo[4] [7]),
    .A2(_104_),
    .B1(_106_),
    .B2(\fifo[5] [7]),
    .ZN(_150_)
  );
  AOI222_X1 _370_ (
    .A1(\fifo[1] [7]),
    .A2(_102_),
    .B1(_105_),
    .B2(\fifo[3] [7]),
    .C1(_108_),
    .C2(\fifo[2] [7]),
    .ZN(_151_)
  );
  AOI222_X1 _371_ (
    .A1(\fifo[6] [7]),
    .A2(_103_),
    .B1(_109_),
    .B2(\fifo[7] [7]),
    .C1(_107_),
    .C2(\fifo[0] [7]),
    .ZN(_152_)
  );
  NAND3_X1 _372_ (
    .A1(_150_),
    .A2(_151_),
    .A3(_152_),
    .ZN(_153_)
  );
  MUX2_X1 _373_ (
    .A(data_out[7]),
    .B(_153_),
    .S(_101_),
    .Z(_075_)
  );
  XNOR2_X1 _374_ (
    .A(read_pointer[3]),
    .B(_139_),
    .ZN(_076_)
  );
  MUX2_X1 _375_ (
    .A(data_in[7]),
    .B(\fifo[6] [7]),
    .S(_141_),
    .Z(_077_)
  );
  MUX2_X1 _376_ (
    .A(data_in[7]),
    .B(\fifo[5] [7]),
    .S(_142_),
    .Z(_078_)
  );
  XNOR2_X1 _377_ (
    .A(write_pointer[3]),
    .B(_144_),
    .ZN(_079_)
  );
  MUX2_X1 _378_ (
    .A(data_in[7]),
    .B(\fifo[3] [7]),
    .S(_147_),
    .Z(_080_)
  );
  MUX2_X1 _379_ (
    .A(data_in[7]),
    .B(\fifo[4] [7]),
    .S(_149_),
    .Z(_081_)
  );
  MUX2_X1 _380_ (
    .A(data_in[7]),
    .B(\fifo[1] [7]),
    .S(_094_),
    .Z(_082_)
  );
  MUX2_X1 _381_ (
    .A(data_in[7]),
    .B(\fifo[0] [7]),
    .S(_148_),
    .Z(_083_)
  );
  DFF_X1 _382_ (
    .CK(clk),
    .D(_072_),
    .Q(\fifo[4] [0]),
    .QN(_165_)
  );
  DFF_X1 _383_ (
    .CK(clk),
    .D(_071_),
    .Q(\fifo[4] [1]),
    .QN(_166_)
  );
  DFF_X1 _384_ (
    .CK(clk),
    .D(_070_),
    .Q(\fifo[4] [2]),
    .QN(_167_)
  );
  DFF_X1 _385_ (
    .CK(clk),
    .D(_069_),
    .Q(\fifo[4] [3]),
    .QN(_168_)
  );
  DFF_X1 _386_ (
    .CK(clk),
    .D(_068_),
    .Q(\fifo[4] [4]),
    .QN(_169_)
  );
  DFF_X1 _387_ (
    .CK(clk),
    .D(_067_),
    .Q(\fifo[4] [5]),
    .QN(_170_)
  );
  DFF_X1 _388_ (
    .CK(clk),
    .D(_066_),
    .Q(\fifo[4] [6]),
    .QN(_171_)
  );
  DFF_X1 _389_ (
    .CK(clk),
    .D(_081_),
    .Q(\fifo[4] [7]),
    .QN(_156_)
  );
  DFF_X1 _390_ (
    .CK(clk),
    .D(_065_),
    .Q(\fifo[0] [0]),
    .QN(_172_)
  );
  DFF_X1 _391_ (
    .CK(clk),
    .D(_064_),
    .Q(\fifo[0] [1]),
    .QN(_173_)
  );
  DFF_X1 _392_ (
    .CK(clk),
    .D(_063_),
    .Q(\fifo[0] [2]),
    .QN(_174_)
  );
  DFF_X1 _393_ (
    .CK(clk),
    .D(_062_),
    .Q(\fifo[0] [3]),
    .QN(_175_)
  );
  DFF_X1 _394_ (
    .CK(clk),
    .D(_061_),
    .Q(\fifo[0] [4]),
    .QN(_176_)
  );
  DFF_X1 _395_ (
    .CK(clk),
    .D(_060_),
    .Q(\fifo[0] [5]),
    .QN(_177_)
  );
  DFF_X1 _396_ (
    .CK(clk),
    .D(_059_),
    .Q(\fifo[0] [6]),
    .QN(_178_)
  );
  DFF_X1 _397_ (
    .CK(clk),
    .D(_083_),
    .Q(\fifo[0] [7]),
    .QN(_154_)
  );
  DFF_X1 _398_ (
    .CK(clk),
    .D(_058_),
    .Q(\fifo[3] [0]),
    .QN(_179_)
  );
  DFF_X1 _399_ (
    .CK(clk),
    .D(_057_),
    .Q(\fifo[3] [1]),
    .QN(_180_)
  );
  DFF_X1 _400_ (
    .CK(clk),
    .D(_056_),
    .Q(\fifo[3] [2]),
    .QN(_181_)
  );
  DFF_X1 _401_ (
    .CK(clk),
    .D(_055_),
    .Q(\fifo[3] [3]),
    .QN(_182_)
  );
  DFF_X1 _402_ (
    .CK(clk),
    .D(_054_),
    .Q(\fifo[3] [4]),
    .QN(_183_)
  );
  DFF_X1 _403_ (
    .CK(clk),
    .D(_053_),
    .Q(\fifo[3] [5]),
    .QN(_184_)
  );
  DFF_X1 _404_ (
    .CK(clk),
    .D(_052_),
    .Q(\fifo[3] [6]),
    .QN(_185_)
  );
  DFF_X1 _405_ (
    .CK(clk),
    .D(_080_),
    .Q(\fifo[3] [7]),
    .QN(_157_)
  );
  DFFR_X1 _406_ (
    .CK(clk),
    .D(_051_),
    .Q(write_pointer[0]),
    .QN(_228_[0]),
    .RN(rst_n)
  );
  DFFR_X1 _407_ (
    .CK(clk),
    .D(_050_),
    .Q(write_pointer[1]),
    .QN(_000_),
    .RN(rst_n)
  );
  DFFR_X1 _408_ (
    .CK(clk),
    .D(_049_),
    .Q(write_pointer[2]),
    .QN(_001_),
    .RN(rst_n)
  );
  DFFR_X1 _409_ (
    .CK(clk),
    .D(_079_),
    .Q(write_pointer[3]),
    .QN(_158_),
    .RN(rst_n)
  );
  DFF_X1 _410_ (
    .CK(clk),
    .D(_048_),
    .Q(\fifo[5] [0]),
    .QN(_186_)
  );
  DFF_X1 _411_ (
    .CK(clk),
    .D(_047_),
    .Q(\fifo[5] [1]),
    .QN(_187_)
  );
  DFF_X1 _412_ (
    .CK(clk),
    .D(_046_),
    .Q(\fifo[5] [2]),
    .QN(_188_)
  );
  DFF_X1 _413_ (
    .CK(clk),
    .D(_045_),
    .Q(\fifo[5] [3]),
    .QN(_189_)
  );
  DFF_X1 _414_ (
    .CK(clk),
    .D(_044_),
    .Q(\fifo[5] [4]),
    .QN(_190_)
  );
  DFF_X1 _415_ (
    .CK(clk),
    .D(_043_),
    .Q(\fifo[5] [5]),
    .QN(_191_)
  );
  DFF_X1 _416_ (
    .CK(clk),
    .D(_042_),
    .Q(\fifo[5] [6]),
    .QN(_192_)
  );
  DFF_X1 _417_ (
    .CK(clk),
    .D(_078_),
    .Q(\fifo[5] [7]),
    .QN(_159_)
  );
  DFF_X1 _418_ (
    .CK(clk),
    .D(_041_),
    .Q(\fifo[6] [0]),
    .QN(_193_)
  );
  DFF_X1 _419_ (
    .CK(clk),
    .D(_040_),
    .Q(\fifo[6] [1]),
    .QN(_194_)
  );
  DFF_X1 _420_ (
    .CK(clk),
    .D(_039_),
    .Q(\fifo[6] [2]),
    .QN(_195_)
  );
  DFF_X1 _421_ (
    .CK(clk),
    .D(_038_),
    .Q(\fifo[6] [3]),
    .QN(_196_)
  );
  DFF_X1 _422_ (
    .CK(clk),
    .D(_037_),
    .Q(\fifo[6] [4]),
    .QN(_197_)
  );
  DFF_X1 _423_ (
    .CK(clk),
    .D(_036_),
    .Q(\fifo[6] [5]),
    .QN(_198_)
  );
  DFF_X1 _424_ (
    .CK(clk),
    .D(_035_),
    .Q(\fifo[6] [6]),
    .QN(_199_)
  );
  DFF_X1 _425_ (
    .CK(clk),
    .D(_077_),
    .Q(\fifo[6] [7]),
    .QN(_160_)
  );
  DFFR_X1 _426_ (
    .CK(clk),
    .D(_034_),
    .Q(read_pointer[0]),
    .QN(_229_[0]),
    .RN(rst_n)
  );
  DFFR_X1 _427_ (
    .CK(clk),
    .D(_033_),
    .Q(read_pointer[1]),
    .QN(_002_),
    .RN(rst_n)
  );
  DFFR_X1 _428_ (
    .CK(clk),
    .D(_032_),
    .Q(read_pointer[2]),
    .QN(_003_),
    .RN(rst_n)
  );
  DFFR_X1 _429_ (
    .CK(clk),
    .D(_076_),
    .Q(read_pointer[3]),
    .QN(_161_),
    .RN(rst_n)
  );
  DFFR_X1 _430_ (
    .CK(clk),
    .D(_031_),
    .Q(data_out[0]),
    .QN(_200_),
    .RN(rst_n)
  );
  DFFR_X1 _431_ (
    .CK(clk),
    .D(_030_),
    .Q(data_out[1]),
    .QN(_201_),
    .RN(rst_n)
  );
  DFFR_X1 _432_ (
    .CK(clk),
    .D(_029_),
    .Q(data_out[2]),
    .QN(_202_),
    .RN(rst_n)
  );
  DFFR_X1 _433_ (
    .CK(clk),
    .D(_028_),
    .Q(data_out[3]),
    .QN(_203_),
    .RN(rst_n)
  );
  DFFR_X1 _434_ (
    .CK(clk),
    .D(_027_),
    .Q(data_out[4]),
    .QN(_204_),
    .RN(rst_n)
  );
  DFFR_X1 _435_ (
    .CK(clk),
    .D(_026_),
    .Q(data_out[5]),
    .QN(_205_),
    .RN(rst_n)
  );
  DFFR_X1 _436_ (
    .CK(clk),
    .D(_025_),
    .Q(data_out[6]),
    .QN(_206_),
    .RN(rst_n)
  );
  DFFR_X1 _437_ (
    .CK(clk),
    .D(_075_),
    .Q(data_out[7]),
    .QN(_162_),
    .RN(rst_n)
  );
  DFF_X1 _438_ (
    .CK(clk),
    .D(_024_),
    .Q(\fifo[7] [0]),
    .QN(_207_)
  );
  DFF_X1 _439_ (
    .CK(clk),
    .D(_023_),
    .Q(\fifo[7] [1]),
    .QN(_208_)
  );
  DFF_X1 _440_ (
    .CK(clk),
    .D(_022_),
    .Q(\fifo[7] [2]),
    .QN(_209_)
  );
  DFF_X1 _441_ (
    .CK(clk),
    .D(_021_),
    .Q(\fifo[7] [3]),
    .QN(_210_)
  );
  DFF_X1 _442_ (
    .CK(clk),
    .D(_020_),
    .Q(\fifo[7] [4]),
    .QN(_211_)
  );
  DFF_X1 _443_ (
    .CK(clk),
    .D(_019_),
    .Q(\fifo[7] [5]),
    .QN(_212_)
  );
  DFF_X1 _444_ (
    .CK(clk),
    .D(_018_),
    .Q(\fifo[7] [6]),
    .QN(_213_)
  );
  DFF_X1 _445_ (
    .CK(clk),
    .D(_074_),
    .Q(\fifo[7] [7]),
    .QN(_163_)
  );
  DFF_X1 _446_ (
    .CK(clk),
    .D(_017_),
    .Q(\fifo[2] [0]),
    .QN(_214_)
  );
  DFF_X1 _447_ (
    .CK(clk),
    .D(_016_),
    .Q(\fifo[2] [1]),
    .QN(_215_)
  );
  DFF_X1 _448_ (
    .CK(clk),
    .D(_015_),
    .Q(\fifo[2] [2]),
    .QN(_216_)
  );
  DFF_X1 _449_ (
    .CK(clk),
    .D(_014_),
    .Q(\fifo[2] [3]),
    .QN(_217_)
  );
  DFF_X1 _450_ (
    .CK(clk),
    .D(_013_),
    .Q(\fifo[2] [4]),
    .QN(_218_)
  );
  DFF_X1 _451_ (
    .CK(clk),
    .D(_012_),
    .Q(\fifo[2] [5]),
    .QN(_219_)
  );
  DFF_X1 _452_ (
    .CK(clk),
    .D(_011_),
    .Q(\fifo[2] [6]),
    .QN(_220_)
  );
  DFF_X1 _453_ (
    .CK(clk),
    .D(_073_),
    .Q(\fifo[2] [7]),
    .QN(_164_)
  );
  DFF_X1 _454_ (
    .CK(clk),
    .D(_010_),
    .Q(\fifo[1] [0]),
    .QN(_221_)
  );
  DFF_X1 _455_ (
    .CK(clk),
    .D(_009_),
    .Q(\fifo[1] [1]),
    .QN(_222_)
  );
  DFF_X1 _456_ (
    .CK(clk),
    .D(_008_),
    .Q(\fifo[1] [2]),
    .QN(_223_)
  );
  DFF_X1 _457_ (
    .CK(clk),
    .D(_007_),
    .Q(\fifo[1] [3]),
    .QN(_224_)
  );
  DFF_X1 _458_ (
    .CK(clk),
    .D(_006_),
    .Q(\fifo[1] [4]),
    .QN(_225_)
  );
  DFF_X1 _459_ (
    .CK(clk),
    .D(_005_),
    .Q(\fifo[1] [5]),
    .QN(_226_)
  );
  DFF_X1 _460_ (
    .CK(clk),
    .D(_004_),
    .Q(\fifo[1] [6]),
    .QN(_227_)
  );
  DFF_X1 _461_ (
    .CK(clk),
    .D(_082_),
    .Q(\fifo[1] [7]),
    .QN(_155_)
  );
  assign _229_[3:1] = read_pointer[3:1];
  assign _228_[3:1] = write_pointer[3:1];
endmodule
